OAUTH1_VERSION_TAG = '1.0'
OAUTH2_VERSION_TAG = '2.0'

K_OAUTH_CLIENT_ID = 'CLIENT_ID'
K_OAUTH_CLIENT_SECRET = 'CLIENT_SECRET'
K_OAUTH_CALLBACK_URL = 'CALLBACK_URL'
K_OAUTH_TOKEN_URL = 'TOKEN_URL'
K_OAUTH_AUTH_URL = 'AUTHORIZATION_URL'
K_POST_SIGN_URL = 'POST_SIGNIN_URL'

K_OAUTH_PROVIDER_ID = 'provider_id'
K_OAUTH_TOKEN_SESSION = 'token_session_key'
K_STATE_SESSION = 'state_session_key'
K_OAUTH_RESULT = 'oauth_result'
